---
- set_fact:
    net_backup_root: "./backup"
  when: net_backup_root is not defined
 
- set_fact:
    net_backup_file: "{{ net_backup_root }}/{{ inventory_hostname }}"

- set_fact:
    net_backup_force: false
  when: net_backup_force is not defined

- name: Check to see if the backup file exists
  stat:
    path: "{{ net_backup_file }}" 
  register: stat_result

- block:
  - include_tasks: "{{ role_path }}/tasks/{{ ansible_network_os }}-backup-config.yml"

  - name: Copy the temp to the destination
    copy:
      src: "{{ temp_backup_file }}"
      dest: "{{ net_backup_file }}"
      force: "{{ net_backup_force | default('no') }}"
    changed_when: False

  - name: Delete the temp file 
    file:
      path: "{{ temp_backup_file }}"
      state: absent
    changed_when: False

  when: (stat_result.stat.exists == 'False') or (net_backup_force == 'true')

- include: "{{ role_path }}/tasks/{{ ansible_network_os }}-diff-config.yml"
  when: stat_result.stat.exists == True
